workflows:
  ios-build:
    name: Bygg iOS-app
    max_build_duration: 15
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Installera beroenden
        script: flutter pub get
      - name: Bygg release .ipa
        script: flutter build ios --release
    artifacts:
      - build/ios/iphoneos/*.ipa
